// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"pont/ent/predicate"
	"pont/ent/setting"
	"pont/ent/tunnel"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeSetting = "Setting"
	TypeTunnel  = "Tunnel"
)

// SettingMutation represents an operation that mutates the Setting nodes in the graph.
type SettingMutation struct {
	config
	op            Op
	typ           string
	id            *int
	key           *string
	value         *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Setting, error)
	predicates    []predicate.Setting
}

var _ ent.Mutation = (*SettingMutation)(nil)

// settingOption allows management of the mutation configuration using functional options.
type settingOption func(*SettingMutation)

// newSettingMutation creates new mutation for the Setting entity.
func newSettingMutation(c config, op Op, opts ...settingOption) *SettingMutation {
	m := &SettingMutation{
		config:        c,
		op:            op,
		typ:           TypeSetting,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withSettingID sets the ID field of the mutation.
func withSettingID(id int) settingOption {
	return func(m *SettingMutation) {
		var (
			err   error
			once  sync.Once
			value *Setting
		)
		m.oldValue = func(ctx context.Context) (*Setting, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Setting.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withSetting sets the old Setting of the mutation.
func withSetting(node *Setting) settingOption {
	return func(m *SettingMutation) {
		m.oldValue = func(context.Context) (*Setting, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m SettingMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m SettingMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *SettingMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *SettingMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Setting.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetKey sets the "key" field.
func (m *SettingMutation) SetKey(s string) {
	m.key = &s
}

// Key returns the value of the "key" field in the mutation.
func (m *SettingMutation) Key() (r string, exists bool) {
	v := m.key
	if v == nil {
		return
	}
	return *v, true
}

// OldKey returns the old "key" field's value of the Setting entity.
// If the Setting object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SettingMutation) OldKey(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldKey is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldKey requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldKey: %w", err)
	}
	return oldValue.Key, nil
}

// ResetKey resets all changes to the "key" field.
func (m *SettingMutation) ResetKey() {
	m.key = nil
}

// SetValue sets the "value" field.
func (m *SettingMutation) SetValue(s string) {
	m.value = &s
}

// Value returns the value of the "value" field in the mutation.
func (m *SettingMutation) Value() (r string, exists bool) {
	v := m.value
	if v == nil {
		return
	}
	return *v, true
}

// OldValue returns the old "value" field's value of the Setting entity.
// If the Setting object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SettingMutation) OldValue(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldValue is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldValue requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldValue: %w", err)
	}
	return oldValue.Value, nil
}

// ResetValue resets all changes to the "value" field.
func (m *SettingMutation) ResetValue() {
	m.value = nil
}

// Where appends a list predicates to the SettingMutation builder.
func (m *SettingMutation) Where(ps ...predicate.Setting) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the SettingMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *SettingMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Setting, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *SettingMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *SettingMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Setting).
func (m *SettingMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *SettingMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.key != nil {
		fields = append(fields, setting.FieldKey)
	}
	if m.value != nil {
		fields = append(fields, setting.FieldValue)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *SettingMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case setting.FieldKey:
		return m.Key()
	case setting.FieldValue:
		return m.Value()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *SettingMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case setting.FieldKey:
		return m.OldKey(ctx)
	case setting.FieldValue:
		return m.OldValue(ctx)
	}
	return nil, fmt.Errorf("unknown Setting field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SettingMutation) SetField(name string, value ent.Value) error {
	switch name {
	case setting.FieldKey:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetKey(v)
		return nil
	case setting.FieldValue:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetValue(v)
		return nil
	}
	return fmt.Errorf("unknown Setting field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *SettingMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *SettingMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SettingMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Setting numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *SettingMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *SettingMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *SettingMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Setting nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *SettingMutation) ResetField(name string) error {
	switch name {
	case setting.FieldKey:
		m.ResetKey()
		return nil
	case setting.FieldValue:
		m.ResetValue()
		return nil
	}
	return fmt.Errorf("unknown Setting field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *SettingMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *SettingMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *SettingMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *SettingMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *SettingMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *SettingMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *SettingMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Setting unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *SettingMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Setting edge %s", name)
}

// TunnelMutation represents an operation that mutates the Tunnel nodes in the graph.
type TunnelMutation struct {
	config
	op              Op
	typ             string
	id              *uuid.UUID
	name            *string
	_type           *tunnel.Type
	target          *string
	enabled         *bool
	mcp_enabled     *bool
	created_at      *time.Time
	updated_at      *time.Time
	ngrok_authtoken *string
	ngrok_domain    *string
	clearedFields   map[string]struct{}
	done            bool
	oldValue        func(context.Context) (*Tunnel, error)
	predicates      []predicate.Tunnel
}

var _ ent.Mutation = (*TunnelMutation)(nil)

// tunnelOption allows management of the mutation configuration using functional options.
type tunnelOption func(*TunnelMutation)

// newTunnelMutation creates new mutation for the Tunnel entity.
func newTunnelMutation(c config, op Op, opts ...tunnelOption) *TunnelMutation {
	m := &TunnelMutation{
		config:        c,
		op:            op,
		typ:           TypeTunnel,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withTunnelID sets the ID field of the mutation.
func withTunnelID(id uuid.UUID) tunnelOption {
	return func(m *TunnelMutation) {
		var (
			err   error
			once  sync.Once
			value *Tunnel
		)
		m.oldValue = func(ctx context.Context) (*Tunnel, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Tunnel.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withTunnel sets the old Tunnel of the mutation.
func withTunnel(node *Tunnel) tunnelOption {
	return func(m *TunnelMutation) {
		m.oldValue = func(context.Context) (*Tunnel, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m TunnelMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m TunnelMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Tunnel entities.
func (m *TunnelMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *TunnelMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *TunnelMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Tunnel.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *TunnelMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *TunnelMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Tunnel entity.
// If the Tunnel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TunnelMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *TunnelMutation) ResetName() {
	m.name = nil
}

// SetType sets the "type" field.
func (m *TunnelMutation) SetType(t tunnel.Type) {
	m._type = &t
}

// GetType returns the value of the "type" field in the mutation.
func (m *TunnelMutation) GetType() (r tunnel.Type, exists bool) {
	v := m._type
	if v == nil {
		return
	}
	return *v, true
}

// OldType returns the old "type" field's value of the Tunnel entity.
// If the Tunnel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TunnelMutation) OldType(ctx context.Context) (v tunnel.Type, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldType: %w", err)
	}
	return oldValue.Type, nil
}

// ResetType resets all changes to the "type" field.
func (m *TunnelMutation) ResetType() {
	m._type = nil
}

// SetTarget sets the "target" field.
func (m *TunnelMutation) SetTarget(s string) {
	m.target = &s
}

// Target returns the value of the "target" field in the mutation.
func (m *TunnelMutation) Target() (r string, exists bool) {
	v := m.target
	if v == nil {
		return
	}
	return *v, true
}

// OldTarget returns the old "target" field's value of the Tunnel entity.
// If the Tunnel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TunnelMutation) OldTarget(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTarget is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTarget requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTarget: %w", err)
	}
	return oldValue.Target, nil
}

// ResetTarget resets all changes to the "target" field.
func (m *TunnelMutation) ResetTarget() {
	m.target = nil
}

// SetEnabled sets the "enabled" field.
func (m *TunnelMutation) SetEnabled(b bool) {
	m.enabled = &b
}

// Enabled returns the value of the "enabled" field in the mutation.
func (m *TunnelMutation) Enabled() (r bool, exists bool) {
	v := m.enabled
	if v == nil {
		return
	}
	return *v, true
}

// OldEnabled returns the old "enabled" field's value of the Tunnel entity.
// If the Tunnel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TunnelMutation) OldEnabled(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEnabled is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEnabled requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEnabled: %w", err)
	}
	return oldValue.Enabled, nil
}

// ResetEnabled resets all changes to the "enabled" field.
func (m *TunnelMutation) ResetEnabled() {
	m.enabled = nil
}

// SetMcpEnabled sets the "mcp_enabled" field.
func (m *TunnelMutation) SetMcpEnabled(b bool) {
	m.mcp_enabled = &b
}

// McpEnabled returns the value of the "mcp_enabled" field in the mutation.
func (m *TunnelMutation) McpEnabled() (r bool, exists bool) {
	v := m.mcp_enabled
	if v == nil {
		return
	}
	return *v, true
}

// OldMcpEnabled returns the old "mcp_enabled" field's value of the Tunnel entity.
// If the Tunnel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TunnelMutation) OldMcpEnabled(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMcpEnabled is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMcpEnabled requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMcpEnabled: %w", err)
	}
	return oldValue.McpEnabled, nil
}

// ResetMcpEnabled resets all changes to the "mcp_enabled" field.
func (m *TunnelMutation) ResetMcpEnabled() {
	m.mcp_enabled = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *TunnelMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *TunnelMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Tunnel entity.
// If the Tunnel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TunnelMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *TunnelMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *TunnelMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *TunnelMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Tunnel entity.
// If the Tunnel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TunnelMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *TunnelMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetNgrokAuthtoken sets the "ngrok_authtoken" field.
func (m *TunnelMutation) SetNgrokAuthtoken(s string) {
	m.ngrok_authtoken = &s
}

// NgrokAuthtoken returns the value of the "ngrok_authtoken" field in the mutation.
func (m *TunnelMutation) NgrokAuthtoken() (r string, exists bool) {
	v := m.ngrok_authtoken
	if v == nil {
		return
	}
	return *v, true
}

// OldNgrokAuthtoken returns the old "ngrok_authtoken" field's value of the Tunnel entity.
// If the Tunnel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TunnelMutation) OldNgrokAuthtoken(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNgrokAuthtoken is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNgrokAuthtoken requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNgrokAuthtoken: %w", err)
	}
	return oldValue.NgrokAuthtoken, nil
}

// ClearNgrokAuthtoken clears the value of the "ngrok_authtoken" field.
func (m *TunnelMutation) ClearNgrokAuthtoken() {
	m.ngrok_authtoken = nil
	m.clearedFields[tunnel.FieldNgrokAuthtoken] = struct{}{}
}

// NgrokAuthtokenCleared returns if the "ngrok_authtoken" field was cleared in this mutation.
func (m *TunnelMutation) NgrokAuthtokenCleared() bool {
	_, ok := m.clearedFields[tunnel.FieldNgrokAuthtoken]
	return ok
}

// ResetNgrokAuthtoken resets all changes to the "ngrok_authtoken" field.
func (m *TunnelMutation) ResetNgrokAuthtoken() {
	m.ngrok_authtoken = nil
	delete(m.clearedFields, tunnel.FieldNgrokAuthtoken)
}

// SetNgrokDomain sets the "ngrok_domain" field.
func (m *TunnelMutation) SetNgrokDomain(s string) {
	m.ngrok_domain = &s
}

// NgrokDomain returns the value of the "ngrok_domain" field in the mutation.
func (m *TunnelMutation) NgrokDomain() (r string, exists bool) {
	v := m.ngrok_domain
	if v == nil {
		return
	}
	return *v, true
}

// OldNgrokDomain returns the old "ngrok_domain" field's value of the Tunnel entity.
// If the Tunnel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TunnelMutation) OldNgrokDomain(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNgrokDomain is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNgrokDomain requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNgrokDomain: %w", err)
	}
	return oldValue.NgrokDomain, nil
}

// ClearNgrokDomain clears the value of the "ngrok_domain" field.
func (m *TunnelMutation) ClearNgrokDomain() {
	m.ngrok_domain = nil
	m.clearedFields[tunnel.FieldNgrokDomain] = struct{}{}
}

// NgrokDomainCleared returns if the "ngrok_domain" field was cleared in this mutation.
func (m *TunnelMutation) NgrokDomainCleared() bool {
	_, ok := m.clearedFields[tunnel.FieldNgrokDomain]
	return ok
}

// ResetNgrokDomain resets all changes to the "ngrok_domain" field.
func (m *TunnelMutation) ResetNgrokDomain() {
	m.ngrok_domain = nil
	delete(m.clearedFields, tunnel.FieldNgrokDomain)
}

// Where appends a list predicates to the TunnelMutation builder.
func (m *TunnelMutation) Where(ps ...predicate.Tunnel) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the TunnelMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *TunnelMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Tunnel, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *TunnelMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *TunnelMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Tunnel).
func (m *TunnelMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *TunnelMutation) Fields() []string {
	fields := make([]string, 0, 9)
	if m.name != nil {
		fields = append(fields, tunnel.FieldName)
	}
	if m._type != nil {
		fields = append(fields, tunnel.FieldType)
	}
	if m.target != nil {
		fields = append(fields, tunnel.FieldTarget)
	}
	if m.enabled != nil {
		fields = append(fields, tunnel.FieldEnabled)
	}
	if m.mcp_enabled != nil {
		fields = append(fields, tunnel.FieldMcpEnabled)
	}
	if m.created_at != nil {
		fields = append(fields, tunnel.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, tunnel.FieldUpdatedAt)
	}
	if m.ngrok_authtoken != nil {
		fields = append(fields, tunnel.FieldNgrokAuthtoken)
	}
	if m.ngrok_domain != nil {
		fields = append(fields, tunnel.FieldNgrokDomain)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *TunnelMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case tunnel.FieldName:
		return m.Name()
	case tunnel.FieldType:
		return m.GetType()
	case tunnel.FieldTarget:
		return m.Target()
	case tunnel.FieldEnabled:
		return m.Enabled()
	case tunnel.FieldMcpEnabled:
		return m.McpEnabled()
	case tunnel.FieldCreatedAt:
		return m.CreatedAt()
	case tunnel.FieldUpdatedAt:
		return m.UpdatedAt()
	case tunnel.FieldNgrokAuthtoken:
		return m.NgrokAuthtoken()
	case tunnel.FieldNgrokDomain:
		return m.NgrokDomain()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *TunnelMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case tunnel.FieldName:
		return m.OldName(ctx)
	case tunnel.FieldType:
		return m.OldType(ctx)
	case tunnel.FieldTarget:
		return m.OldTarget(ctx)
	case tunnel.FieldEnabled:
		return m.OldEnabled(ctx)
	case tunnel.FieldMcpEnabled:
		return m.OldMcpEnabled(ctx)
	case tunnel.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case tunnel.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case tunnel.FieldNgrokAuthtoken:
		return m.OldNgrokAuthtoken(ctx)
	case tunnel.FieldNgrokDomain:
		return m.OldNgrokDomain(ctx)
	}
	return nil, fmt.Errorf("unknown Tunnel field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TunnelMutation) SetField(name string, value ent.Value) error {
	switch name {
	case tunnel.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case tunnel.FieldType:
		v, ok := value.(tunnel.Type)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetType(v)
		return nil
	case tunnel.FieldTarget:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTarget(v)
		return nil
	case tunnel.FieldEnabled:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEnabled(v)
		return nil
	case tunnel.FieldMcpEnabled:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMcpEnabled(v)
		return nil
	case tunnel.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case tunnel.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case tunnel.FieldNgrokAuthtoken:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNgrokAuthtoken(v)
		return nil
	case tunnel.FieldNgrokDomain:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNgrokDomain(v)
		return nil
	}
	return fmt.Errorf("unknown Tunnel field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *TunnelMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *TunnelMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TunnelMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Tunnel numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *TunnelMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(tunnel.FieldNgrokAuthtoken) {
		fields = append(fields, tunnel.FieldNgrokAuthtoken)
	}
	if m.FieldCleared(tunnel.FieldNgrokDomain) {
		fields = append(fields, tunnel.FieldNgrokDomain)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *TunnelMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *TunnelMutation) ClearField(name string) error {
	switch name {
	case tunnel.FieldNgrokAuthtoken:
		m.ClearNgrokAuthtoken()
		return nil
	case tunnel.FieldNgrokDomain:
		m.ClearNgrokDomain()
		return nil
	}
	return fmt.Errorf("unknown Tunnel nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *TunnelMutation) ResetField(name string) error {
	switch name {
	case tunnel.FieldName:
		m.ResetName()
		return nil
	case tunnel.FieldType:
		m.ResetType()
		return nil
	case tunnel.FieldTarget:
		m.ResetTarget()
		return nil
	case tunnel.FieldEnabled:
		m.ResetEnabled()
		return nil
	case tunnel.FieldMcpEnabled:
		m.ResetMcpEnabled()
		return nil
	case tunnel.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case tunnel.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case tunnel.FieldNgrokAuthtoken:
		m.ResetNgrokAuthtoken()
		return nil
	case tunnel.FieldNgrokDomain:
		m.ResetNgrokDomain()
		return nil
	}
	return fmt.Errorf("unknown Tunnel field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *TunnelMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *TunnelMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *TunnelMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *TunnelMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *TunnelMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *TunnelMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *TunnelMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Tunnel unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *TunnelMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Tunnel edge %s", name)
}
