// Code generated by ent, DO NOT EDIT.

package ent

import (
	"pont/ent/schema"
	"pont/ent/tunnel"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	tunnelFields := schema.Tunnel{}.Fields()
	_ = tunnelFields
	// tunnelDescEnabled is the schema descriptor for enabled field.
	tunnelDescEnabled := tunnelFields[4].Descriptor()
	// tunnel.DefaultEnabled holds the default value on creation for the enabled field.
	tunnel.DefaultEnabled = tunnelDescEnabled.Default.(bool)
	// tunnelDescMcpEnabled is the schema descriptor for mcp_enabled field.
	tunnelDescMcpEnabled := tunnelFields[5].Descriptor()
	// tunnel.DefaultMcpEnabled holds the default value on creation for the mcp_enabled field.
	tunnel.DefaultMcpEnabled = tunnelDescMcpEnabled.Default.(bool)
	// tunnelDescCreatedAt is the schema descriptor for created_at field.
	tunnelDescCreatedAt := tunnelFields[6].Descriptor()
	// tunnel.DefaultCreatedAt holds the default value on creation for the created_at field.
	tunnel.DefaultCreatedAt = tunnelDescCreatedAt.Default.(func() time.Time)
	// tunnelDescUpdatedAt is the schema descriptor for updated_at field.
	tunnelDescUpdatedAt := tunnelFields[7].Descriptor()
	// tunnel.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tunnel.DefaultUpdatedAt = tunnelDescUpdatedAt.Default.(func() time.Time)
	// tunnel.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tunnel.UpdateDefaultUpdatedAt = tunnelDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tunnelDescID is the schema descriptor for id field.
	tunnelDescID := tunnelFields[0].Descriptor()
	// tunnel.DefaultID holds the default value on creation for the id field.
	tunnel.DefaultID = tunnelDescID.Default.(func() uuid.UUID)
}
