// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"pont/ent/tunnel"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// TunnelCreate is the builder for creating a Tunnel entity.
type TunnelCreate struct {
	config
	mutation *TunnelMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (tc *TunnelCreate) SetName(s string) *TunnelCreate {
	tc.mutation.SetName(s)
	return tc
}

// SetType sets the "type" field.
func (tc *TunnelCreate) SetType(t tunnel.Type) *TunnelCreate {
	tc.mutation.SetType(t)
	return tc
}

// SetTarget sets the "target" field.
func (tc *TunnelCreate) SetTarget(s string) *TunnelCreate {
	tc.mutation.SetTarget(s)
	return tc
}

// SetEnabled sets the "enabled" field.
func (tc *TunnelCreate) SetEnabled(b bool) *TunnelCreate {
	tc.mutation.SetEnabled(b)
	return tc
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (tc *TunnelCreate) SetNillableEnabled(b *bool) *TunnelCreate {
	if b != nil {
		tc.SetEnabled(*b)
	}
	return tc
}

// SetCreatedAt sets the "created_at" field.
func (tc *TunnelCreate) SetCreatedAt(t time.Time) *TunnelCreate {
	tc.mutation.SetCreatedAt(t)
	return tc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tc *TunnelCreate) SetNillableCreatedAt(t *time.Time) *TunnelCreate {
	if t != nil {
		tc.SetCreatedAt(*t)
	}
	return tc
}

// SetUpdatedAt sets the "updated_at" field.
func (tc *TunnelCreate) SetUpdatedAt(t time.Time) *TunnelCreate {
	tc.mutation.SetUpdatedAt(t)
	return tc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tc *TunnelCreate) SetNillableUpdatedAt(t *time.Time) *TunnelCreate {
	if t != nil {
		tc.SetUpdatedAt(*t)
	}
	return tc
}

// SetNgrokAuthtoken sets the "ngrok_authtoken" field.
func (tc *TunnelCreate) SetNgrokAuthtoken(s string) *TunnelCreate {
	tc.mutation.SetNgrokAuthtoken(s)
	return tc
}

// SetNillableNgrokAuthtoken sets the "ngrok_authtoken" field if the given value is not nil.
func (tc *TunnelCreate) SetNillableNgrokAuthtoken(s *string) *TunnelCreate {
	if s != nil {
		tc.SetNgrokAuthtoken(*s)
	}
	return tc
}

// SetNgrokDomain sets the "ngrok_domain" field.
func (tc *TunnelCreate) SetNgrokDomain(s string) *TunnelCreate {
	tc.mutation.SetNgrokDomain(s)
	return tc
}

// SetNillableNgrokDomain sets the "ngrok_domain" field if the given value is not nil.
func (tc *TunnelCreate) SetNillableNgrokDomain(s *string) *TunnelCreate {
	if s != nil {
		tc.SetNgrokDomain(*s)
	}
	return tc
}

// SetID sets the "id" field.
func (tc *TunnelCreate) SetID(u uuid.UUID) *TunnelCreate {
	tc.mutation.SetID(u)
	return tc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (tc *TunnelCreate) SetNillableID(u *uuid.UUID) *TunnelCreate {
	if u != nil {
		tc.SetID(*u)
	}
	return tc
}

// Mutation returns the TunnelMutation object of the builder.
func (tc *TunnelCreate) Mutation() *TunnelMutation {
	return tc.mutation
}

// Save creates the Tunnel in the database.
func (tc *TunnelCreate) Save(ctx context.Context) (*Tunnel, error) {
	tc.defaults()
	return withHooks(ctx, tc.sqlSave, tc.mutation, tc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TunnelCreate) SaveX(ctx context.Context) *Tunnel {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *TunnelCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *TunnelCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tc *TunnelCreate) defaults() {
	if _, ok := tc.mutation.Enabled(); !ok {
		v := tunnel.DefaultEnabled
		tc.mutation.SetEnabled(v)
	}
	if _, ok := tc.mutation.CreatedAt(); !ok {
		v := tunnel.DefaultCreatedAt()
		tc.mutation.SetCreatedAt(v)
	}
	if _, ok := tc.mutation.UpdatedAt(); !ok {
		v := tunnel.DefaultUpdatedAt()
		tc.mutation.SetUpdatedAt(v)
	}
	if _, ok := tc.mutation.ID(); !ok {
		v := tunnel.DefaultID()
		tc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *TunnelCreate) check() error {
	if _, ok := tc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Tunnel.name"`)}
	}
	if _, ok := tc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Tunnel.type"`)}
	}
	if v, ok := tc.mutation.GetType(); ok {
		if err := tunnel.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Tunnel.type": %w`, err)}
		}
	}
	if _, ok := tc.mutation.Target(); !ok {
		return &ValidationError{Name: "target", err: errors.New(`ent: missing required field "Tunnel.target"`)}
	}
	if _, ok := tc.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "Tunnel.enabled"`)}
	}
	if _, ok := tc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Tunnel.created_at"`)}
	}
	if _, ok := tc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Tunnel.updated_at"`)}
	}
	return nil
}

func (tc *TunnelCreate) sqlSave(ctx context.Context) (*Tunnel, error) {
	if err := tc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	tc.mutation.id = &_node.ID
	tc.mutation.done = true
	return _node, nil
}

func (tc *TunnelCreate) createSpec() (*Tunnel, *sqlgraph.CreateSpec) {
	var (
		_node = &Tunnel{config: tc.config}
		_spec = sqlgraph.NewCreateSpec(tunnel.Table, sqlgraph.NewFieldSpec(tunnel.FieldID, field.TypeUUID))
	)
	if id, ok := tc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := tc.mutation.Name(); ok {
		_spec.SetField(tunnel.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := tc.mutation.GetType(); ok {
		_spec.SetField(tunnel.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := tc.mutation.Target(); ok {
		_spec.SetField(tunnel.FieldTarget, field.TypeString, value)
		_node.Target = value
	}
	if value, ok := tc.mutation.Enabled(); ok {
		_spec.SetField(tunnel.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := tc.mutation.CreatedAt(); ok {
		_spec.SetField(tunnel.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := tc.mutation.UpdatedAt(); ok {
		_spec.SetField(tunnel.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := tc.mutation.NgrokAuthtoken(); ok {
		_spec.SetField(tunnel.FieldNgrokAuthtoken, field.TypeString, value)
		_node.NgrokAuthtoken = &value
	}
	if value, ok := tc.mutation.NgrokDomain(); ok {
		_spec.SetField(tunnel.FieldNgrokDomain, field.TypeString, value)
		_node.NgrokDomain = &value
	}
	return _node, _spec
}

// TunnelCreateBulk is the builder for creating many Tunnel entities in bulk.
type TunnelCreateBulk struct {
	config
	err      error
	builders []*TunnelCreate
}

// Save creates the Tunnel entities in the database.
func (tcb *TunnelCreateBulk) Save(ctx context.Context) ([]*Tunnel, error) {
	if tcb.err != nil {
		return nil, tcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Tunnel, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TunnelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *TunnelCreateBulk) SaveX(ctx context.Context) []*Tunnel {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *TunnelCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *TunnelCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
