// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"pont/ent/predicate"
	"pont/ent/tunnel"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TunnelUpdate is the builder for updating Tunnel entities.
type TunnelUpdate struct {
	config
	hooks    []Hook
	mutation *TunnelMutation
}

// Where appends a list predicates to the TunnelUpdate builder.
func (tu *TunnelUpdate) Where(ps ...predicate.Tunnel) *TunnelUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetName sets the "name" field.
func (tu *TunnelUpdate) SetName(s string) *TunnelUpdate {
	tu.mutation.SetName(s)
	return tu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tu *TunnelUpdate) SetNillableName(s *string) *TunnelUpdate {
	if s != nil {
		tu.SetName(*s)
	}
	return tu
}

// SetType sets the "type" field.
func (tu *TunnelUpdate) SetType(t tunnel.Type) *TunnelUpdate {
	tu.mutation.SetType(t)
	return tu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (tu *TunnelUpdate) SetNillableType(t *tunnel.Type) *TunnelUpdate {
	if t != nil {
		tu.SetType(*t)
	}
	return tu
}

// SetTarget sets the "target" field.
func (tu *TunnelUpdate) SetTarget(s string) *TunnelUpdate {
	tu.mutation.SetTarget(s)
	return tu
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (tu *TunnelUpdate) SetNillableTarget(s *string) *TunnelUpdate {
	if s != nil {
		tu.SetTarget(*s)
	}
	return tu
}

// SetEnabled sets the "enabled" field.
func (tu *TunnelUpdate) SetEnabled(b bool) *TunnelUpdate {
	tu.mutation.SetEnabled(b)
	return tu
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (tu *TunnelUpdate) SetNillableEnabled(b *bool) *TunnelUpdate {
	if b != nil {
		tu.SetEnabled(*b)
	}
	return tu
}

// SetUpdatedAt sets the "updated_at" field.
func (tu *TunnelUpdate) SetUpdatedAt(t time.Time) *TunnelUpdate {
	tu.mutation.SetUpdatedAt(t)
	return tu
}

// SetNgrokAuthtoken sets the "ngrok_authtoken" field.
func (tu *TunnelUpdate) SetNgrokAuthtoken(s string) *TunnelUpdate {
	tu.mutation.SetNgrokAuthtoken(s)
	return tu
}

// SetNillableNgrokAuthtoken sets the "ngrok_authtoken" field if the given value is not nil.
func (tu *TunnelUpdate) SetNillableNgrokAuthtoken(s *string) *TunnelUpdate {
	if s != nil {
		tu.SetNgrokAuthtoken(*s)
	}
	return tu
}

// ClearNgrokAuthtoken clears the value of the "ngrok_authtoken" field.
func (tu *TunnelUpdate) ClearNgrokAuthtoken() *TunnelUpdate {
	tu.mutation.ClearNgrokAuthtoken()
	return tu
}

// SetNgrokDomain sets the "ngrok_domain" field.
func (tu *TunnelUpdate) SetNgrokDomain(s string) *TunnelUpdate {
	tu.mutation.SetNgrokDomain(s)
	return tu
}

// SetNillableNgrokDomain sets the "ngrok_domain" field if the given value is not nil.
func (tu *TunnelUpdate) SetNillableNgrokDomain(s *string) *TunnelUpdate {
	if s != nil {
		tu.SetNgrokDomain(*s)
	}
	return tu
}

// ClearNgrokDomain clears the value of the "ngrok_domain" field.
func (tu *TunnelUpdate) ClearNgrokDomain() *TunnelUpdate {
	tu.mutation.ClearNgrokDomain()
	return tu
}

// Mutation returns the TunnelMutation object of the builder.
func (tu *TunnelUpdate) Mutation() *TunnelMutation {
	return tu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *TunnelUpdate) Save(ctx context.Context) (int, error) {
	tu.defaults()
	return withHooks(ctx, tu.sqlSave, tu.mutation, tu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TunnelUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TunnelUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TunnelUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tu *TunnelUpdate) defaults() {
	if _, ok := tu.mutation.UpdatedAt(); !ok {
		v := tunnel.UpdateDefaultUpdatedAt()
		tu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tu *TunnelUpdate) check() error {
	if v, ok := tu.mutation.GetType(); ok {
		if err := tunnel.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Tunnel.type": %w`, err)}
		}
	}
	return nil
}

func (tu *TunnelUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(tunnel.Table, tunnel.Columns, sqlgraph.NewFieldSpec(tunnel.FieldID, field.TypeUUID))
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.Name(); ok {
		_spec.SetField(tunnel.FieldName, field.TypeString, value)
	}
	if value, ok := tu.mutation.GetType(); ok {
		_spec.SetField(tunnel.FieldType, field.TypeEnum, value)
	}
	if value, ok := tu.mutation.Target(); ok {
		_spec.SetField(tunnel.FieldTarget, field.TypeString, value)
	}
	if value, ok := tu.mutation.Enabled(); ok {
		_spec.SetField(tunnel.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := tu.mutation.UpdatedAt(); ok {
		_spec.SetField(tunnel.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := tu.mutation.NgrokAuthtoken(); ok {
		_spec.SetField(tunnel.FieldNgrokAuthtoken, field.TypeString, value)
	}
	if tu.mutation.NgrokAuthtokenCleared() {
		_spec.ClearField(tunnel.FieldNgrokAuthtoken, field.TypeString)
	}
	if value, ok := tu.mutation.NgrokDomain(); ok {
		_spec.SetField(tunnel.FieldNgrokDomain, field.TypeString, value)
	}
	if tu.mutation.NgrokDomainCleared() {
		_spec.ClearField(tunnel.FieldNgrokDomain, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tunnel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tu.mutation.done = true
	return n, nil
}

// TunnelUpdateOne is the builder for updating a single Tunnel entity.
type TunnelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TunnelMutation
}

// SetName sets the "name" field.
func (tuo *TunnelUpdateOne) SetName(s string) *TunnelUpdateOne {
	tuo.mutation.SetName(s)
	return tuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tuo *TunnelUpdateOne) SetNillableName(s *string) *TunnelUpdateOne {
	if s != nil {
		tuo.SetName(*s)
	}
	return tuo
}

// SetType sets the "type" field.
func (tuo *TunnelUpdateOne) SetType(t tunnel.Type) *TunnelUpdateOne {
	tuo.mutation.SetType(t)
	return tuo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (tuo *TunnelUpdateOne) SetNillableType(t *tunnel.Type) *TunnelUpdateOne {
	if t != nil {
		tuo.SetType(*t)
	}
	return tuo
}

// SetTarget sets the "target" field.
func (tuo *TunnelUpdateOne) SetTarget(s string) *TunnelUpdateOne {
	tuo.mutation.SetTarget(s)
	return tuo
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (tuo *TunnelUpdateOne) SetNillableTarget(s *string) *TunnelUpdateOne {
	if s != nil {
		tuo.SetTarget(*s)
	}
	return tuo
}

// SetEnabled sets the "enabled" field.
func (tuo *TunnelUpdateOne) SetEnabled(b bool) *TunnelUpdateOne {
	tuo.mutation.SetEnabled(b)
	return tuo
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (tuo *TunnelUpdateOne) SetNillableEnabled(b *bool) *TunnelUpdateOne {
	if b != nil {
		tuo.SetEnabled(*b)
	}
	return tuo
}

// SetUpdatedAt sets the "updated_at" field.
func (tuo *TunnelUpdateOne) SetUpdatedAt(t time.Time) *TunnelUpdateOne {
	tuo.mutation.SetUpdatedAt(t)
	return tuo
}

// SetNgrokAuthtoken sets the "ngrok_authtoken" field.
func (tuo *TunnelUpdateOne) SetNgrokAuthtoken(s string) *TunnelUpdateOne {
	tuo.mutation.SetNgrokAuthtoken(s)
	return tuo
}

// SetNillableNgrokAuthtoken sets the "ngrok_authtoken" field if the given value is not nil.
func (tuo *TunnelUpdateOne) SetNillableNgrokAuthtoken(s *string) *TunnelUpdateOne {
	if s != nil {
		tuo.SetNgrokAuthtoken(*s)
	}
	return tuo
}

// ClearNgrokAuthtoken clears the value of the "ngrok_authtoken" field.
func (tuo *TunnelUpdateOne) ClearNgrokAuthtoken() *TunnelUpdateOne {
	tuo.mutation.ClearNgrokAuthtoken()
	return tuo
}

// SetNgrokDomain sets the "ngrok_domain" field.
func (tuo *TunnelUpdateOne) SetNgrokDomain(s string) *TunnelUpdateOne {
	tuo.mutation.SetNgrokDomain(s)
	return tuo
}

// SetNillableNgrokDomain sets the "ngrok_domain" field if the given value is not nil.
func (tuo *TunnelUpdateOne) SetNillableNgrokDomain(s *string) *TunnelUpdateOne {
	if s != nil {
		tuo.SetNgrokDomain(*s)
	}
	return tuo
}

// ClearNgrokDomain clears the value of the "ngrok_domain" field.
func (tuo *TunnelUpdateOne) ClearNgrokDomain() *TunnelUpdateOne {
	tuo.mutation.ClearNgrokDomain()
	return tuo
}

// Mutation returns the TunnelMutation object of the builder.
func (tuo *TunnelUpdateOne) Mutation() *TunnelMutation {
	return tuo.mutation
}

// Where appends a list predicates to the TunnelUpdate builder.
func (tuo *TunnelUpdateOne) Where(ps ...predicate.Tunnel) *TunnelUpdateOne {
	tuo.mutation.Where(ps...)
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *TunnelUpdateOne) Select(field string, fields ...string) *TunnelUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Tunnel entity.
func (tuo *TunnelUpdateOne) Save(ctx context.Context) (*Tunnel, error) {
	tuo.defaults()
	return withHooks(ctx, tuo.sqlSave, tuo.mutation, tuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TunnelUpdateOne) SaveX(ctx context.Context) *Tunnel {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *TunnelUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TunnelUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tuo *TunnelUpdateOne) defaults() {
	if _, ok := tuo.mutation.UpdatedAt(); !ok {
		v := tunnel.UpdateDefaultUpdatedAt()
		tuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tuo *TunnelUpdateOne) check() error {
	if v, ok := tuo.mutation.GetType(); ok {
		if err := tunnel.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Tunnel.type": %w`, err)}
		}
	}
	return nil
}

func (tuo *TunnelUpdateOne) sqlSave(ctx context.Context) (_node *Tunnel, err error) {
	if err := tuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tunnel.Table, tunnel.Columns, sqlgraph.NewFieldSpec(tunnel.FieldID, field.TypeUUID))
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Tunnel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tunnel.FieldID)
		for _, f := range fields {
			if !tunnel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tunnel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.Name(); ok {
		_spec.SetField(tunnel.FieldName, field.TypeString, value)
	}
	if value, ok := tuo.mutation.GetType(); ok {
		_spec.SetField(tunnel.FieldType, field.TypeEnum, value)
	}
	if value, ok := tuo.mutation.Target(); ok {
		_spec.SetField(tunnel.FieldTarget, field.TypeString, value)
	}
	if value, ok := tuo.mutation.Enabled(); ok {
		_spec.SetField(tunnel.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := tuo.mutation.UpdatedAt(); ok {
		_spec.SetField(tunnel.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := tuo.mutation.NgrokAuthtoken(); ok {
		_spec.SetField(tunnel.FieldNgrokAuthtoken, field.TypeString, value)
	}
	if tuo.mutation.NgrokAuthtokenCleared() {
		_spec.ClearField(tunnel.FieldNgrokAuthtoken, field.TypeString)
	}
	if value, ok := tuo.mutation.NgrokDomain(); ok {
		_spec.SetField(tunnel.FieldNgrokDomain, field.TypeString, value)
	}
	if tuo.mutation.NgrokDomainCleared() {
		_spec.ClearField(tunnel.FieldNgrokDomain, field.TypeString)
	}
	_node = &Tunnel{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tunnel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tuo.mutation.done = true
	return _node, nil
}
