// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"pont/ent/predicate"
	"pont/ent/tunnel"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TunnelUpdate is the builder for updating Tunnel entities.
type TunnelUpdate struct {
	config
	hooks    []Hook
	mutation *TunnelMutation
}

// Where appends a list predicates to the TunnelUpdate builder.
func (_u *TunnelUpdate) Where(ps ...predicate.Tunnel) *TunnelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *TunnelUpdate) SetName(v string) *TunnelUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TunnelUpdate) SetNillableName(v *string) *TunnelUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *TunnelUpdate) SetType(v tunnel.Type) *TunnelUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *TunnelUpdate) SetNillableType(v *tunnel.Type) *TunnelUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetTarget sets the "target" field.
func (_u *TunnelUpdate) SetTarget(v string) *TunnelUpdate {
	_u.mutation.SetTarget(v)
	return _u
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_u *TunnelUpdate) SetNillableTarget(v *string) *TunnelUpdate {
	if v != nil {
		_u.SetTarget(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *TunnelUpdate) SetEnabled(v bool) *TunnelUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *TunnelUpdate) SetNillableEnabled(v *bool) *TunnelUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetMcpEnabled sets the "mcp_enabled" field.
func (_u *TunnelUpdate) SetMcpEnabled(v bool) *TunnelUpdate {
	_u.mutation.SetMcpEnabled(v)
	return _u
}

// SetNillableMcpEnabled sets the "mcp_enabled" field if the given value is not nil.
func (_u *TunnelUpdate) SetNillableMcpEnabled(v *bool) *TunnelUpdate {
	if v != nil {
		_u.SetMcpEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TunnelUpdate) SetUpdatedAt(v time.Time) *TunnelUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNgrokAuthtoken sets the "ngrok_authtoken" field.
func (_u *TunnelUpdate) SetNgrokAuthtoken(v string) *TunnelUpdate {
	_u.mutation.SetNgrokAuthtoken(v)
	return _u
}

// SetNillableNgrokAuthtoken sets the "ngrok_authtoken" field if the given value is not nil.
func (_u *TunnelUpdate) SetNillableNgrokAuthtoken(v *string) *TunnelUpdate {
	if v != nil {
		_u.SetNgrokAuthtoken(*v)
	}
	return _u
}

// ClearNgrokAuthtoken clears the value of the "ngrok_authtoken" field.
func (_u *TunnelUpdate) ClearNgrokAuthtoken() *TunnelUpdate {
	_u.mutation.ClearNgrokAuthtoken()
	return _u
}

// SetNgrokDomain sets the "ngrok_domain" field.
func (_u *TunnelUpdate) SetNgrokDomain(v string) *TunnelUpdate {
	_u.mutation.SetNgrokDomain(v)
	return _u
}

// SetNillableNgrokDomain sets the "ngrok_domain" field if the given value is not nil.
func (_u *TunnelUpdate) SetNillableNgrokDomain(v *string) *TunnelUpdate {
	if v != nil {
		_u.SetNgrokDomain(*v)
	}
	return _u
}

// ClearNgrokDomain clears the value of the "ngrok_domain" field.
func (_u *TunnelUpdate) ClearNgrokDomain() *TunnelUpdate {
	_u.mutation.ClearNgrokDomain()
	return _u
}

// Mutation returns the TunnelMutation object of the builder.
func (_u *TunnelUpdate) Mutation() *TunnelMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TunnelUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TunnelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TunnelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TunnelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TunnelUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tunnel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TunnelUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := tunnel.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Tunnel.type": %w`, err)}
		}
	}
	return nil
}

func (_u *TunnelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tunnel.Table, tunnel.Columns, sqlgraph.NewFieldSpec(tunnel.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tunnel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(tunnel.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Target(); ok {
		_spec.SetField(tunnel.FieldTarget, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(tunnel.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.McpEnabled(); ok {
		_spec.SetField(tunnel.FieldMcpEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tunnel.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.NgrokAuthtoken(); ok {
		_spec.SetField(tunnel.FieldNgrokAuthtoken, field.TypeString, value)
	}
	if _u.mutation.NgrokAuthtokenCleared() {
		_spec.ClearField(tunnel.FieldNgrokAuthtoken, field.TypeString)
	}
	if value, ok := _u.mutation.NgrokDomain(); ok {
		_spec.SetField(tunnel.FieldNgrokDomain, field.TypeString, value)
	}
	if _u.mutation.NgrokDomainCleared() {
		_spec.ClearField(tunnel.FieldNgrokDomain, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tunnel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TunnelUpdateOne is the builder for updating a single Tunnel entity.
type TunnelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TunnelMutation
}

// SetName sets the "name" field.
func (_u *TunnelUpdateOne) SetName(v string) *TunnelUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TunnelUpdateOne) SetNillableName(v *string) *TunnelUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *TunnelUpdateOne) SetType(v tunnel.Type) *TunnelUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *TunnelUpdateOne) SetNillableType(v *tunnel.Type) *TunnelUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetTarget sets the "target" field.
func (_u *TunnelUpdateOne) SetTarget(v string) *TunnelUpdateOne {
	_u.mutation.SetTarget(v)
	return _u
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_u *TunnelUpdateOne) SetNillableTarget(v *string) *TunnelUpdateOne {
	if v != nil {
		_u.SetTarget(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *TunnelUpdateOne) SetEnabled(v bool) *TunnelUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *TunnelUpdateOne) SetNillableEnabled(v *bool) *TunnelUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetMcpEnabled sets the "mcp_enabled" field.
func (_u *TunnelUpdateOne) SetMcpEnabled(v bool) *TunnelUpdateOne {
	_u.mutation.SetMcpEnabled(v)
	return _u
}

// SetNillableMcpEnabled sets the "mcp_enabled" field if the given value is not nil.
func (_u *TunnelUpdateOne) SetNillableMcpEnabled(v *bool) *TunnelUpdateOne {
	if v != nil {
		_u.SetMcpEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TunnelUpdateOne) SetUpdatedAt(v time.Time) *TunnelUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNgrokAuthtoken sets the "ngrok_authtoken" field.
func (_u *TunnelUpdateOne) SetNgrokAuthtoken(v string) *TunnelUpdateOne {
	_u.mutation.SetNgrokAuthtoken(v)
	return _u
}

// SetNillableNgrokAuthtoken sets the "ngrok_authtoken" field if the given value is not nil.
func (_u *TunnelUpdateOne) SetNillableNgrokAuthtoken(v *string) *TunnelUpdateOne {
	if v != nil {
		_u.SetNgrokAuthtoken(*v)
	}
	return _u
}

// ClearNgrokAuthtoken clears the value of the "ngrok_authtoken" field.
func (_u *TunnelUpdateOne) ClearNgrokAuthtoken() *TunnelUpdateOne {
	_u.mutation.ClearNgrokAuthtoken()
	return _u
}

// SetNgrokDomain sets the "ngrok_domain" field.
func (_u *TunnelUpdateOne) SetNgrokDomain(v string) *TunnelUpdateOne {
	_u.mutation.SetNgrokDomain(v)
	return _u
}

// SetNillableNgrokDomain sets the "ngrok_domain" field if the given value is not nil.
func (_u *TunnelUpdateOne) SetNillableNgrokDomain(v *string) *TunnelUpdateOne {
	if v != nil {
		_u.SetNgrokDomain(*v)
	}
	return _u
}

// ClearNgrokDomain clears the value of the "ngrok_domain" field.
func (_u *TunnelUpdateOne) ClearNgrokDomain() *TunnelUpdateOne {
	_u.mutation.ClearNgrokDomain()
	return _u
}

// Mutation returns the TunnelMutation object of the builder.
func (_u *TunnelUpdateOne) Mutation() *TunnelMutation {
	return _u.mutation
}

// Where appends a list predicates to the TunnelUpdate builder.
func (_u *TunnelUpdateOne) Where(ps ...predicate.Tunnel) *TunnelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TunnelUpdateOne) Select(field string, fields ...string) *TunnelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Tunnel entity.
func (_u *TunnelUpdateOne) Save(ctx context.Context) (*Tunnel, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TunnelUpdateOne) SaveX(ctx context.Context) *Tunnel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TunnelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TunnelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TunnelUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tunnel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TunnelUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := tunnel.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Tunnel.type": %w`, err)}
		}
	}
	return nil
}

func (_u *TunnelUpdateOne) sqlSave(ctx context.Context) (_node *Tunnel, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tunnel.Table, tunnel.Columns, sqlgraph.NewFieldSpec(tunnel.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Tunnel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tunnel.FieldID)
		for _, f := range fields {
			if !tunnel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tunnel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tunnel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(tunnel.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Target(); ok {
		_spec.SetField(tunnel.FieldTarget, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(tunnel.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.McpEnabled(); ok {
		_spec.SetField(tunnel.FieldMcpEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tunnel.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.NgrokAuthtoken(); ok {
		_spec.SetField(tunnel.FieldNgrokAuthtoken, field.TypeString, value)
	}
	if _u.mutation.NgrokAuthtokenCleared() {
		_spec.ClearField(tunnel.FieldNgrokAuthtoken, field.TypeString)
	}
	if value, ok := _u.mutation.NgrokDomain(); ok {
		_spec.SetField(tunnel.FieldNgrokDomain, field.TypeString, value)
	}
	if _u.mutation.NgrokDomainCleared() {
		_spec.ClearField(tunnel.FieldNgrokDomain, field.TypeString)
	}
	_node = &Tunnel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tunnel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
