// Code generated by ent, DO NOT EDIT.

package tunnel

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the tunnel type in the database.
	Label = "tunnel"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldTarget holds the string denoting the target field in the database.
	FieldTarget = "target"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldMcpEnabled holds the string denoting the mcp_enabled field in the database.
	FieldMcpEnabled = "mcp_enabled"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldNgrokAuthtoken holds the string denoting the ngrok_authtoken field in the database.
	FieldNgrokAuthtoken = "ngrok_authtoken"
	// FieldNgrokDomain holds the string denoting the ngrok_domain field in the database.
	FieldNgrokDomain = "ngrok_domain"
	// Table holds the table name of the tunnel in the database.
	Table = "tunnels"
)

// Columns holds all SQL columns for tunnel fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldType,
	FieldTarget,
	FieldEnabled,
	FieldMcpEnabled,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldNgrokAuthtoken,
	FieldNgrokDomain,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultMcpEnabled holds the default value on creation for the "mcp_enabled" field.
	DefaultMcpEnabled bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Type defines the type for the "type" enum field.
type Type string

// Type values.
const (
	TypeCloudflare Type = "cloudflare"
	TypeNgrok      Type = "ngrok"
)

func (_type Type) String() string {
	return string(_type)
}

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type Type) error {
	switch _type {
	case TypeCloudflare, TypeNgrok:
		return nil
	default:
		return fmt.Errorf("tunnel: invalid enum value for type field: %q", _type)
	}
}

// OrderOption defines the ordering options for the Tunnel queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByTarget orders the results by the target field.
func ByTarget(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTarget, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByMcpEnabled orders the results by the mcp_enabled field.
func ByMcpEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMcpEnabled, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByNgrokAuthtoken orders the results by the ngrok_authtoken field.
func ByNgrokAuthtoken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNgrokAuthtoken, opts...).ToFunc()
}

// ByNgrokDomain orders the results by the ngrok_domain field.
func ByNgrokDomain(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNgrokDomain, opts...).ToFunc()
}
