// Code generated by ent, DO NOT EDIT.

package tunnel

import (
	"pont/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldEQ(FieldName, v))
}

// Target applies equality check predicate on the "target" field. It's identical to TargetEQ.
func Target(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldEQ(FieldTarget, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldEQ(FieldEnabled, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldEQ(FieldUpdatedAt, v))
}

// NgrokAuthtoken applies equality check predicate on the "ngrok_authtoken" field. It's identical to NgrokAuthtokenEQ.
func NgrokAuthtoken(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldEQ(FieldNgrokAuthtoken, v))
}

// NgrokDomain applies equality check predicate on the "ngrok_domain" field. It's identical to NgrokDomainEQ.
func NgrokDomain(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldEQ(FieldNgrokDomain, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldContainsFold(FieldName, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldNotIn(FieldType, vs...))
}

// TargetEQ applies the EQ predicate on the "target" field.
func TargetEQ(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldEQ(FieldTarget, v))
}

// TargetNEQ applies the NEQ predicate on the "target" field.
func TargetNEQ(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldNEQ(FieldTarget, v))
}

// TargetIn applies the In predicate on the "target" field.
func TargetIn(vs ...string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldIn(FieldTarget, vs...))
}

// TargetNotIn applies the NotIn predicate on the "target" field.
func TargetNotIn(vs ...string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldNotIn(FieldTarget, vs...))
}

// TargetGT applies the GT predicate on the "target" field.
func TargetGT(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldGT(FieldTarget, v))
}

// TargetGTE applies the GTE predicate on the "target" field.
func TargetGTE(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldGTE(FieldTarget, v))
}

// TargetLT applies the LT predicate on the "target" field.
func TargetLT(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldLT(FieldTarget, v))
}

// TargetLTE applies the LTE predicate on the "target" field.
func TargetLTE(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldLTE(FieldTarget, v))
}

// TargetContains applies the Contains predicate on the "target" field.
func TargetContains(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldContains(FieldTarget, v))
}

// TargetHasPrefix applies the HasPrefix predicate on the "target" field.
func TargetHasPrefix(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldHasPrefix(FieldTarget, v))
}

// TargetHasSuffix applies the HasSuffix predicate on the "target" field.
func TargetHasSuffix(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldHasSuffix(FieldTarget, v))
}

// TargetEqualFold applies the EqualFold predicate on the "target" field.
func TargetEqualFold(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldEqualFold(FieldTarget, v))
}

// TargetContainsFold applies the ContainsFold predicate on the "target" field.
func TargetContainsFold(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldContainsFold(FieldTarget, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldNEQ(FieldEnabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldLTE(FieldUpdatedAt, v))
}

// NgrokAuthtokenEQ applies the EQ predicate on the "ngrok_authtoken" field.
func NgrokAuthtokenEQ(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldEQ(FieldNgrokAuthtoken, v))
}

// NgrokAuthtokenNEQ applies the NEQ predicate on the "ngrok_authtoken" field.
func NgrokAuthtokenNEQ(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldNEQ(FieldNgrokAuthtoken, v))
}

// NgrokAuthtokenIn applies the In predicate on the "ngrok_authtoken" field.
func NgrokAuthtokenIn(vs ...string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldIn(FieldNgrokAuthtoken, vs...))
}

// NgrokAuthtokenNotIn applies the NotIn predicate on the "ngrok_authtoken" field.
func NgrokAuthtokenNotIn(vs ...string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldNotIn(FieldNgrokAuthtoken, vs...))
}

// NgrokAuthtokenGT applies the GT predicate on the "ngrok_authtoken" field.
func NgrokAuthtokenGT(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldGT(FieldNgrokAuthtoken, v))
}

// NgrokAuthtokenGTE applies the GTE predicate on the "ngrok_authtoken" field.
func NgrokAuthtokenGTE(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldGTE(FieldNgrokAuthtoken, v))
}

// NgrokAuthtokenLT applies the LT predicate on the "ngrok_authtoken" field.
func NgrokAuthtokenLT(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldLT(FieldNgrokAuthtoken, v))
}

// NgrokAuthtokenLTE applies the LTE predicate on the "ngrok_authtoken" field.
func NgrokAuthtokenLTE(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldLTE(FieldNgrokAuthtoken, v))
}

// NgrokAuthtokenContains applies the Contains predicate on the "ngrok_authtoken" field.
func NgrokAuthtokenContains(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldContains(FieldNgrokAuthtoken, v))
}

// NgrokAuthtokenHasPrefix applies the HasPrefix predicate on the "ngrok_authtoken" field.
func NgrokAuthtokenHasPrefix(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldHasPrefix(FieldNgrokAuthtoken, v))
}

// NgrokAuthtokenHasSuffix applies the HasSuffix predicate on the "ngrok_authtoken" field.
func NgrokAuthtokenHasSuffix(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldHasSuffix(FieldNgrokAuthtoken, v))
}

// NgrokAuthtokenIsNil applies the IsNil predicate on the "ngrok_authtoken" field.
func NgrokAuthtokenIsNil() predicate.Tunnel {
	return predicate.Tunnel(sql.FieldIsNull(FieldNgrokAuthtoken))
}

// NgrokAuthtokenNotNil applies the NotNil predicate on the "ngrok_authtoken" field.
func NgrokAuthtokenNotNil() predicate.Tunnel {
	return predicate.Tunnel(sql.FieldNotNull(FieldNgrokAuthtoken))
}

// NgrokAuthtokenEqualFold applies the EqualFold predicate on the "ngrok_authtoken" field.
func NgrokAuthtokenEqualFold(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldEqualFold(FieldNgrokAuthtoken, v))
}

// NgrokAuthtokenContainsFold applies the ContainsFold predicate on the "ngrok_authtoken" field.
func NgrokAuthtokenContainsFold(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldContainsFold(FieldNgrokAuthtoken, v))
}

// NgrokDomainEQ applies the EQ predicate on the "ngrok_domain" field.
func NgrokDomainEQ(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldEQ(FieldNgrokDomain, v))
}

// NgrokDomainNEQ applies the NEQ predicate on the "ngrok_domain" field.
func NgrokDomainNEQ(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldNEQ(FieldNgrokDomain, v))
}

// NgrokDomainIn applies the In predicate on the "ngrok_domain" field.
func NgrokDomainIn(vs ...string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldIn(FieldNgrokDomain, vs...))
}

// NgrokDomainNotIn applies the NotIn predicate on the "ngrok_domain" field.
func NgrokDomainNotIn(vs ...string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldNotIn(FieldNgrokDomain, vs...))
}

// NgrokDomainGT applies the GT predicate on the "ngrok_domain" field.
func NgrokDomainGT(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldGT(FieldNgrokDomain, v))
}

// NgrokDomainGTE applies the GTE predicate on the "ngrok_domain" field.
func NgrokDomainGTE(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldGTE(FieldNgrokDomain, v))
}

// NgrokDomainLT applies the LT predicate on the "ngrok_domain" field.
func NgrokDomainLT(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldLT(FieldNgrokDomain, v))
}

// NgrokDomainLTE applies the LTE predicate on the "ngrok_domain" field.
func NgrokDomainLTE(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldLTE(FieldNgrokDomain, v))
}

// NgrokDomainContains applies the Contains predicate on the "ngrok_domain" field.
func NgrokDomainContains(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldContains(FieldNgrokDomain, v))
}

// NgrokDomainHasPrefix applies the HasPrefix predicate on the "ngrok_domain" field.
func NgrokDomainHasPrefix(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldHasPrefix(FieldNgrokDomain, v))
}

// NgrokDomainHasSuffix applies the HasSuffix predicate on the "ngrok_domain" field.
func NgrokDomainHasSuffix(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldHasSuffix(FieldNgrokDomain, v))
}

// NgrokDomainIsNil applies the IsNil predicate on the "ngrok_domain" field.
func NgrokDomainIsNil() predicate.Tunnel {
	return predicate.Tunnel(sql.FieldIsNull(FieldNgrokDomain))
}

// NgrokDomainNotNil applies the NotNil predicate on the "ngrok_domain" field.
func NgrokDomainNotNil() predicate.Tunnel {
	return predicate.Tunnel(sql.FieldNotNull(FieldNgrokDomain))
}

// NgrokDomainEqualFold applies the EqualFold predicate on the "ngrok_domain" field.
func NgrokDomainEqualFold(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldEqualFold(FieldNgrokDomain, v))
}

// NgrokDomainContainsFold applies the ContainsFold predicate on the "ngrok_domain" field.
func NgrokDomainContainsFold(v string) predicate.Tunnel {
	return predicate.Tunnel(sql.FieldContainsFold(FieldNgrokDomain, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Tunnel) predicate.Tunnel {
	return predicate.Tunnel(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Tunnel) predicate.Tunnel {
	return predicate.Tunnel(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Tunnel) predicate.Tunnel {
	return predicate.Tunnel(sql.NotPredicates(p))
}
