// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Setting is the predicate function for setting builders.
type Setting func(*sql.Selector)

// Tunnel is the predicate function for tunnel builders.
type Tunnel func(*sql.Selector)
